try:
    a = 35/7
except Exception as e:
    print(e)

else:   #Else block will always when there is no error in try block
    print("Program executed Successfully")